language: node_js
node_js:
  - "lts/*"
  - "8"
before_install: npm -g i greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm run build
  - npm test
after_script: greenkeeper-lockfile-upload